/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_JniUtil */

#ifndef _Included_com_example_hellojni_JniUtil
#define _Included_com_example_hellojni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_JniUtil
 * Method:    getPersonName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_JniUtil_getPersonName
  (JNIEnv *, jclass);

/*
 * Class:     com_example_hellojni_JniUtil
 * Method:    updateFilePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_hellojni_JniUtil_updateFilePath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_hellojni_JniUtil
 * Method:    updateIntArray
 * Signature: ([I)V
 */
JNIEXPORT jintArray JNICALL Java_com_example_hellojni_JniUtil_updateIntArray
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
